### ISSUE TITLE
请问有QQ交流群吗?还有视频很模糊哦

### ISSUE THREAD

**Issue by mengzhisuoliu** [iUIShop/LibUIDK#1]
请问有QQ交流群吗?还有视频很模糊哦

**Comment by iUIShop** [comment]
视频应该可以选择高清模式吧。你可以加我QQ直接问问题。或者加群282795382，不过讨论LibUIDK的很少。




------------------
 
Thanks.
 
BRs
 
（Scott.Liu）刘树伟  | 北京优艾斯普科技有限公司 http://www.iuishop.com
 
CTO
 
Tel: 13521795231 | QQ: 1584793892



 




------------------ 原始邮件 ------------------
发件人: "mengzhisuoliu"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 下午2:56
收件人: "iUIShop/LibUIDK"<LibUIDK@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [iUIShop/LibUIDK] 请问有QQ交流群吗?还有视频很模糊哦 (#1)




请问有QQ交流群吗?还有视频很模糊哦

**Comment by mengzhisuoliu** [comment]
高清模式选择不了哦,可能你是视频发布者可以选择哦

**Comment by iUIShop** [comment]
https://share.weiyun.com/5VgCGF1
这里有原版视频教程。


------------------
 
Thanks.
 
BRs
 
（Scott.Liu）刘树伟  | 北京优艾斯普科技有限公司 http://www.iuishop.com
 
CTO
 
Tel: 13521795231 | QQ: 1584793892



 




------------------ 原始邮件 ------------------
发件人: "mengzhisuoliu"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 下午3:13
收件人: "iUIShop/LibUIDK"<LibUIDK@noreply.github.com>;
抄送: "LIBUIDK界面库"<1584793892@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iUIShop/LibUIDK] 请问有QQ交流群吗?还有视频很模糊哦 (#1)




高清模式选择不了哦,可能你是视频发布者可以选择哦
