### ISSUE TITLE
“x64\Debug Static\LibUIDK.pch”: No such file or directory

### ISSUE THREAD

**Issue by TimelifeCzy** [iUIShop/LibUIDK#3]
vs2017编译问题，并没有#include <stdafx.h>找到相关LibUIDK.pch的数据
VS2017项目配置：Debug x64，关闭Sp缓存，共享DLL MFC， SDK:10.0.17134.0 目标平台win10
`.......................
1>f:\libuidk\libuidk\wlbutton.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLIMRichEditCtrl.cpp
1>f:\libuidk\libuidk\wlimricheditctrl.cpp(1): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLLine.cpp
1>f:\libuidk\libuidk\wlline.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLPicture.cpp
1>f:\libuidk\libuidk\wlpicture.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLRichEditCtrl.cpp
1>f:\libuidk\libuidk\wlricheditctrl.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLSliderCtrl.cpp
1>f:\libuidk\libuidk\wlsliderctrl.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>正在生成代码...
1>正在编译...
1>WLSplitterBar.cpp
1>f:\libuidk\libuidk\wlsplitterbar.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLText.cpp
1>f:\libuidk\libuidk\wltext.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
1>WLWnd.cpp
1>f:\libuidk\libuidk\wlwnd.cpp(4): fatal error C1083: 无法打开预编译头文件: “x64\Debug Static\LibUIDK.pch”: No such file or directory
`

**Comment by iUIShop** [comment]
LibUIDK仅有for vs2008和vs2012能编译x64，其它的都只能编译x86。您可以自行修改编译成x64。

**Comment by TimelifeCzy** [comment]
> 
> 
> LibUIDK仅有for vs2008和vs2012能编译x64，其它的都只能编译x86。您可以自行修改编译成x64。

Thank
