### ISSUE TITLE
请问下代码界面分离是如何设置呢?

### ISSUE THREAD

**Issue by dpawsbear** [iUIShop/LibUIDK#5]
平台:win10 + vs2017
请问下视频教程中给的代码和界面分离的宏定义"INIT_MSG_MAP",在VS2017生成的工程已经找不到了,如果是要在VS2017环境中设置代码和界面分离的话,最好的编写方式是什么样子的呢?谢谢

**Comment by iUIShop** [comment]
不建议使用界面代码和功能代码分离方式了。这个意义不太大，但却增加了理解难度。

**Comment by dpawsbear** [comment]
非常感谢,谢谢~
