### ISSUE TITLE
Bug with 64bit UIShop

### ISSUE THREAD

**Issue by fzzn-2020** [iUIShop/LibUIDK#6]
Create a new project and double click the IDW_MAIN node under Windows root node in the fileview pane, the program crushes.
Reason: the TreeControl api calls to "SetItemData" and "GetItemData" should take a DWORD_PTR type  for params dat.
For example: 
m_treeWindow.SetItemData(m_hResourceRoot, (DWORD)pData)
 should be:
 m_treeWindow.SetItemData(m_hResourceRoot, (DWORD_PTR)pData)
To fix the bug:
Replace "(DWORD)pData" with "(DWORD_PTR)pData" project-wise .

**Comment by iUIShop** [comment]
LibUIDK not support 64bit now。
&nbsp;

 
Thanks.</?xml:namespace>
 
BRs
 
（Scott.Liu）刘树伟&nbsp; | 北京优艾斯普科技有限公司 http://www.iuishop.com
 
CTO
 
QQ: 1584793892



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fzzn-2020"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 中午11:38
收件人: "iUIShop/LibUIDK"<LibUIDK@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [iUIShop/LibUIDK] There is a bug with 64bit UIShop (#6)





 
创建一个新项目，然后在文件视图窗格中的Windows根节点下双击IDW_MAIN节点，程序将崩溃。
 原因：TreeControl api对“ SetItemData”和“ GetItemData”的调用对于参数dat应该采用DWORD_PTR类型。
 例如：
 m_treeWindow.SetItemData（m_hResourceRoot，（DWORD）pData）
 应该是：
 m_treeWindow.SetItemData（m_hResourceRoot，（DWORD_PTR）pData）
 要修复该错误：在项目方面
 将“（DWORD）pData”替换为“（DWORD_PTR）pData” 。
 
— 
您收到此消息是因为您已订阅此线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by iUIShop** [comment]
现在VS2019版本的LibUIDK支持x64了。
