### ISSUE TITLE
编译就是通过不了

### ISSUE THREAD

**Issue by zj360202** [iUIShop/LibUIDK#7]
我这边使用了vs2017与vs2019都不行，编译平台是32位的，配置是release unicode static与debug unicode static
安装了v141工具集与v142工具集，也是不行。
请问下，您这边编译的环境是什么。

`在编译到   UIShop.cpp:389行的时候  pMainFrame->UpdateWindow();
总是报  D:\soft\visual_studio\VC\Tools\MSVC\14.27.29110\atlmfc\src\mfc\afxtoolbarimages.cpp:4313
values2[c] += (double)(*pRowSrc2) * weight2;`

`引发了异常: 读取访问权限冲突。
**pRowSrc2** 是 0x3676008。`

**Comment by Bayzh** [comment]
我用vs2015 x64编译通过了，没有遇到你的问题，不过x64运行有问题，还是用32位的
